# volumes:
services:
  mongo:
        image: mongo:5
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
  fastapi-service:
    build:
        context: ./fastapi-service
        dockerfile: ./Dockerfile.dev
    ports:
        - "YOUR PORT NUMBER:8000"
    volumes:
        - ./fastapi-service:/app
    environment:
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: db-name
      WAIT_HOSTS: mongo:27017

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        mongo-data:
          external: true
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
